# Generated by Django 4.2.11 on 2024-05-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userdetails_balance_alter_userdetails_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
