# Generated by Django 4.2.11 on 2024-05-01 01:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_currencyconversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyConversion',
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='moneyInRequestReceiversCurrency',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='moneyInRequestSendersCurrency',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
