# Generated by Django 4.2.11 on 2024-05-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_delete_currencyconversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='notificationType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notificationType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
