# Generated by Django 4.2.11 on 2024-05-01 21:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_moneyrequest_notificationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='notificationType',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amountInReceiversCurrency',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amountInSendersCurrency',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
