# Generated by Django 4.2.11 on 2024-05-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_remove_transaction_notificationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyrequest',
            name='notificationType',
        ),
    ]
