# Generated by Django 4.2.11 on 2024-05-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_remove_moneyrequest_notificationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='reqestReceiverCurrencySign',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='requestSenderCurrencySign',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiverCurrencySign',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='senderCurrencySign',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='moneyrequest',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
